name: flare_flutter
description: Vector design and runtime animation for Flutter.
version: 1.2.2
author: "2Dimensions Team <info@2dimensions.com>"
homepage: https://github.com/2d-inc/Flare-Flutter
environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flare_dart: 
    git:
      url: https://github.com/megasistemas/Flare-Flutter.git
      path: flare_dart
      ref: fix_40_v2
  # flare_dart:
  #   path: ../flare_dart
dev_dependencies:
  flutter_test:
    sdk: flutter